### ISSUE TITLE
How to load pretrained model?

### ISSUE THREAD

**Issue by ekaterina-poslavskaya** [alphacep/vosk-tts#22]
Hi! Thanks for great models.
I'd like to try to finetune with additional voice, but I can't load pretrained model:
torch.load returns pickle error.

What has torch package been used for saving? (there is no requirements file in training catalog)

**Comment by nshmyrev** [comment]
We use torch 2.1. What is the pickle error exactly?

**Comment by ekaterina-poslavskaya** [comment]
I've got Error on loading pretrained model. This error catches by try..except and full train from empty model begans, not finetuning.

Exception has occurred: UnpicklingError
invalid load key, 'v'.
  File "xxx/vosk-tts/training/utils.py", line 20, in load_checkpoint
    checkpoint_dict = torch.load(checkpoint_path, map_location='cpu')
  File "xxx/vosk-tts/training/train_finetune.py", line 210, in run
    _, _, _, _ = utils.load_checkpoint("training/pretrained/G_1000.pth", net_g,
  File "xxx/vosk-tts/training/train_finetune.py", line 61, in main
    run(0, n_gpus, hps)
  File "xxx/training/train_finetune.py", line 503, in <module>
    main()
_pickle.UnpicklingError: invalid load key, 'v'.


in requirements:
torch = "==2.1.0"

**Comment by nshmyrev** [comment]
Are you sure you cloned the model properly? Likely you have issue with git lfs. Check the model size (G_1000.pth), if it is only 135 bytes you need to properly install lfs first.

**Comment by ekaterina-poslavskaya** [comment]
My bad! It works!
