### ISSUE TITLE
Audio hours in the dataset

### ISSUE THREAD

**Issue by Bubarinokk** [alphacep/vosk-tts#24]
How many hours of audio were used to make the Russian language model in GPT-SoVITS?

**Comment by nshmyrev** [comment]
about 1000

**Comment by Bubarinokk** [comment]
Do you have a method for finding several hours of audio in a language?

**Comment by nshmyrev** [comment]
Yes, sure, we can build any language you need.

**Comment by Bubarinokk** [comment]
> Yes, sure, we can build any language you need.

How?

**Comment by nshmyrev** [comment]
You need to tell the language name

**Comment by Bubarinokk** [comment]
> You need to tell the language name

Brazilian Portuguese

**Comment by nshmyrev** [comment]
@Bubarinokk like this https://github.com/Edresson/TTS-Portuguese-Corpus?

**Comment by Bubarinokk** [comment]
> @Bubarinokk like this https://github.com/Edresson/TTS-Portuguese-Corpus?

Yes

**Comment by nshmyrev** [comment]
Please let us know if you have extra questions.
