### ISSUE TITLE
Что-то случилось с файнтюном.

### ISSUE THREAD

**Issue by electrik-spb** [alphacep/vosk-tts#26]
Спасибо за Vosk_TTS. С апреля месяца, я тестирую вашу разработку. Тренировал и сорок минут и четыре часа, в общем всё нормально. После последних  коммитов, при использовании train_finetune получаю пьяные и не адекватные голоса. До этого уменя был заклонирован репозиторий от начала мая. Естественно, пока я понимаю не все внутренности движка. Может что-то можно поправить? Или что-то поменялось в движке, и пока файнтюн работать нормально не будет?

**Comment by nshmyrev** [comment]
Добрый день. Чекпоинты и код только что обновлены, попробуйте

https://huggingface.co/alphacep/vosk-tts-ru-multi
https://github.com/alphacep/vosk-tts/tree/master/training
