### ISSUE TITLE
Are evaluation metrics valid only for English?

### ISSUE THREAD

**Issue by WhiteTeaDragon** [alphacep/vosk-tts#29]
Hello! Thank you very much for this repo. I wanted to know if evaluation methods from the folder "extra" for FAD and similarity only work for English language, as they use models pretrained on English datasets. Should I use some other models for evaluating Russian TTS?

**Comment by nshmyrev** [comment]
We use them for Russian, not English. You can check here:

https://t.me/speech_recognition_ru/57297

![image](https://github.com/user-attachments/assets/fbaf5363-bcb7-4cfb-b29a-e84eddc20ca5)

**Comment by WhiteTeaDragon** [comment]
Thank you! So those models work fine even though they did not see Russian language at training time?

**Comment by nshmyrev** [comment]
Yes, it is ok. Not perfect, but ok for initial estimation. For similarity we are going to move to Voxblink2 embedding soon, they are trained on Russian.

**Comment by WhiteTeaDragon** [comment]
Ok, thank you!

**Comment by WhiteTeaDragon** [comment]
Hello again! Have you heard about tts_scores from Tortoise TTS paper? Have you tried it for Russian language? Here is a link: https://github.com/neonbjb/tts-scores

**Comment by nshmyrev** [comment]
> Hello again! Have you heard about tts_scores from Tortoise TTS paper? 

Yes, sure

> Have you tried it for Russian language?

We are doing more or less the same, we evaluate same FID and WER, on the top we evaluate UTMOS (essentially naturalness) and speaker similarity.
