### ISSUE TITLE
Got an error during the opening of model directory

### ISSUE THREAD

**Issue by artbutakov** [alphacep/vosk-tts#3]
Hello!

Have got an error 

> UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 517: character maps to undefined

trying to create a Model object. Could fix it by adding encoding type to the line #46 in model.py

> for line in open(model_path / "dictionary"_**, encoding='utf8'**_):

**Comment by nshmyrev** [comment]
Fixed in  b4986b783874420a081f36877e2fce9b4b045926

Thank you!
