### ISSUE TITLE
Ударения

### ISSUE THREAD

**Issue by epigraphe** [alphacep/vosk-tts#4]
Прекрасная модель, все замечательно работает.
Как прямо указать ударение в некоторых словах? Пробовал делать заглавную букву или ставить плюс перед гласной - результата нет. 
Спасибо

**Comment by nshmyrev** [comment]
Плюс перед гласной должен работать, с какой фразой не получается?

Что внутри модели есть файл dictionary, можно там поменять

**Comment by epigraphe** [comment]
Да, попробовал еще раз, плюс действительно сработал. Спасибо
