### ISSUE TITLE
Не сбрасывается предыдущая генерация

### ISSUE THREAD

**Issue by epigraphe** [alphacep/vosk-tts#5]
Периодически, не могу понять с какой частотой и логикой, происходит зависание синтезатора.
Иногда помогает ребут, иногда нет.

Наташа вызывается так:
```
[hi]
exten = s,1,Answer()
same = n,Wait(1)
same = n,Set(RHV_FILE=${CALLERID(num)}_${EPOCH})
same = n,Set(RHV_TEXT="Компания привествует Вас, ${CALLERID(Name)}")
same = n,System(/var/lib/asterisk/agi-bin/Robovoice.py ${RHV_FILE} ${RHV_TEXT})
same = n,Playback(/home/asterisk/sounds/${RHV_FILE}&silence/1)
same = n,System(rm -f /home/asterisk/sounds/${RHV_FILE}.wav)
same = n,System(rm -f /home/asterisk/sounds/${RHV_FILE}_t.wav)
```

Сейчас попробовал запустить ее из командной строки тупо скопировав пример отсюда.
В выводе получил
```
[root@freepbx asterisk]# ^C
[root@freepbx asterisk]# vosk-tts -n vosk-model-tts-ru-0.1-natasha --input "Привет мир!" --output ~/out.wav

vosk-tts -n vosk-model-tts-ru-0.1-natasha --input "Привет мир"/home/asterisk/speech/Robovoice.py 9999_1691413691 'Компания приветствует Вас, Иван Иванов'" --output ~/out.wav
> ^C
```
и на этом зависание и выход по ctrl+c

Если я правильно понимаю, предыдущая генерация из диалплана как-то зависла и никуда не девается.
Как перед генерацией очистить предыдущий запрос принудительно?

**Comment by epigraphe** [comment]
Пока вызываю так, вроде не зависает. Будем наблюдать
    
# Generate TTS command and execute it
    command = f"vosk-tts -n vosk-model-tts-ru-0.1-natasha --input '{replaced_text}' --output {temp_audio_path} && sox {temp_audio_path} -c 1 -r 8000 {audio_path}"
    os.system(command)

**Comment by epigraphe** [comment]
Зависло. После ребута всей операционки - работает. Есть ли какой-то дебаг или лог? Не могу отловить почему так происходит

**Comment by nshmyrev** [comment]
зависает что? сервер целиком или процесс.

**Comment by epigraphe** [comment]
Именно это я и пытаюсь отловить. Я толкаю скрипт из диалплана астериск. Скрипт просто не выполняется. Если запускаю его напрямую   из командной строки - срабатывает. Я пытаюсь понять, что именно вызывает сбой. В астериске логов по поводу выполнения этого скрипта нет, вот пытаюсь отловить что вообще приходит и как.

**Comment by nshmyrev** [comment]
Рекомендую использовать сервер/клиент вместо того, чтобы каждый раз запускать команду. Должно быть быстрее

https://github.com/alphacep/vosk-tts/tree/master/server
